"""empty message

Revision ID: ac650e64c654
Revises: 
Create Date: 2025-02-12 13:07:30.628500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac650e64c654'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('play_areas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pfctNm', sa.String(length=255), nullable=False),
    sa.Column('pfctSn', sa.String(length=50), nullable=False),
    sa.Column('instlPlaceCdNm', sa.String(length=255), nullable=True),
    sa.Column('operYnCd', sa.String(length=50), nullable=True),
    sa.Column('operYnCdNm', sa.String(length=255), nullable=True),
    sa.Column('dutyCd', sa.String(length=50), nullable=True),
    sa.Column('dutyCdNm', sa.String(length=255), nullable=True),
    sa.Column('prvtPblcYnCd', sa.String(length=50), nullable=True),
    sa.Column('prvtPblcYnCdNm', sa.String(length=255), nullable=True),
    sa.Column('ronaAddr', sa.String(length=255), nullable=True),
    sa.Column('ronaDaddr', sa.String(length=255), nullable=True),
    sa.Column('instlYmd', sa.String(length=50), nullable=True),
    sa.Column('instlPlaceCd', sa.String(length=50), nullable=True),
    sa.Column('idrodrCd', sa.String(length=50), nullable=True),
    sa.Column('idrodrCdNm', sa.String(length=255), nullable=True),
    sa.Column('rgnCd', sa.String(length=50), nullable=True),
    sa.Column('rgnCdNm', sa.String(length=255), nullable=True),
    sa.Column('latCrtsVl', sa.String(length=50), nullable=True),
    sa.Column('lotCrtsVl', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('play_areas')
    # ### end Alembic commands ###
